@echo off
echo Setting up environment for NeuroScan Frontend...
cd frontend
echo Installing dependencies (if needed)...
call cmd /c npm install
echo Starting Frontend Server...
call cmd /c npm run dev
pause
